extract:
  locations: 
    - SANTA ANITA
  parameters:
    - pm10
    - pm25
  start_date: 2022-01-01T00:00:00Z
  end_date: 2022-12-31T00:00:00Z

load:
  host: localhost
  dbname: air_quality
  user: postgres